# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vercel",
    ".vscode",
    "__pypackages__",
    "__pycache__",
    "migrations",
]

# Same as Black.
line-length = 80
indent-width = 4

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["I", "F", "E", "W", "PL", "PT"]
ignore = ["F401", "PLR0913", "E722"]

[format]
# Like Black, use double quotes for strings.
preview = true
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"