from .heros import STANDARD_CARDS_HEROS
from .miracles import STANDARD_CARDS_MIRACLES
from .artifacts import STANDARD_CARDS_ARTIFACTS

STANDARD_CARDS = [*STANDARD_CARDS_HEROS, *STANDARD_CARDS_MIRACLES, *STANDARD_CARDS_ARTIFACTS]

