STANDARD_CARDS_RAW_DATA = {
    'abraao': ('Abraão', 2, 1, 2),
    'adao': ('Adão', 1, 1, 1),
    'daniel': ('Daniel', 2, 1, 2),
    'davi': ('Davi', 3, 3, 2),
    'elias': ('Elias', 4, 3, 1),
    'ester': ('Ester', 1, 0, 2),
    'eva': ('Eva', 1, 1, 1),
    'jaco': ('Jaco', 2, 2, 2),
    'jose-do-egito': ('José do Egito', 2, 2, 1),
    'josue': ('Josué', 3, 3, 1),
    'maria': ('Maria', 2, 1, 2),
    'moises': ('Moisés', 3, 2, 2),
    'noe': ('Noé', 1, 2, 1),
    'salomao': ('Salomão', 4, 2, 2),
    'sansao': ('Sansão', 6, 5, 5),
    'davi-ssj': ('Davi', 3, 4, 5),
    'josue-ssj': ('Josué', 3, 3, 2),
    'moises-ssj': ('Moisés', 3, 2, 3),
    'arca-da-alianca': ('Arca da Aliança', 5, 0, 0),
    'arca-de-noe': ('Arca de Noé', 5, 0, 0),
    'botas-do-evangelho': ('Botas do Evangelho', 2, 0, 0),
    'cajado-de-moises': ('Cajado de Moisés', 2, 0, 0),
    'capacete-da-salvacao': ('Capacete da Salvação', 1, 0, 0),
    'cinturao-da-verdade': ('Cinturão da Verdade', 4, 0, 0),
    'couraca-da-justica': ('Couraça da Justiça', 3, 0, 0),
    'escudo-da-fe': ('Escudo da Fé', 1, 0, 0),
    'espada-do-espirito': ('Espada do Espírito', 3, 0, 0),
    'os-10-mandamentos': ('Os 10 Mandamentos', 6, 0, 0),
    'fruto-proibido': ('Fruto Proibido', 3, 0, 0),
    'idolatria': ('Idolatria', 2, 0, 0),
    'traicao': ('Traição', 2, 0, 0),
    'cordeiro-de-deus': ('Cordeiro de Deus', 4, 0, 0),
    'diluvio': ('Dilúvio', 6, 0, 0),
    'fogo-do-ceu': ('Fogo do Céu', 3, 0, 0),
    'forca-de-sansao': ('Força de Sansão', 2, 0, 0),
    'liberacao-celestial': ('Liberação Celestial', 2, 0, 0),
    'no-ceu-tem-pao': ('No Céu tem Pão', 3, 0, 0),
    'passagem-segura': ('Passagem Segura', 4, 0, 0),
    'protecao-divina': ('Proteção de  Divina', 1, 0, 0),
    'ressurreicao': ('Ressurreição', 3, 0, 0),
    'restauracao-de-fe': ('Restauração de Fé', 2, 0, 0),
    'sabedoria-de-salomao': ('Sabedoria de Salomão', 1, 0, 0),
    'sarca-ardente': ('Sarça Ardente', 2, 0, 0),
}
