# tipo, nome, _, _, _, sabedoria, ataque, defesa, passiva, ativa, equipável
STANDARD_CARDS = {
    "HEROS": [
        (1, 'Abraão', '', '', '', 2, 1, 2, True, False, False),
        (1, 'Adão', '', '', '', 1, 1, 1, True, False, False),
        (1, 'Daniel', '', '', '', 2, 1, 2, False, True, False),
        (1, 'Davi', '', '', '', 3, 3, 2, False, True, False),
        (1, 'Elias', '', '', '', 4, 3, 1, False, True, False),
        (1, 'Ester', '', '', '', 1, 0, 2, False, True, False),
        (1, 'Eva', '', '', '', 1, 1, 1, False, True, False),
        (1, 'Jaco', '', '', '', 2, 2, 2, False, True, False),
        (1, 'José do Egito', '', '', '', 2, 2, 1, False, True, False),
        (1, 'Josué', '', '', '', 3, 3, 1, False, True, False),
        (1, 'Maria', '', '', '', 2, 1, 2, False, True, False),
        (1, 'Moisés', '', '', '', 3, 2, 2, False, True, False),
        (1, 'Noé', '', '', '', 1, 2, 1, True, False, False),
        (1, 'Salomão', '', '', '', 4, 2, 2, False, True, False),
        (1, 'Sansão', '', '', '', 6, 5, 5, False, True, False),
    ],
    "LEGENDARY": [
        (1, 'Davi', '', '', '', 3, 4, 5, False, True, True),
        (1, 'Josué', '', '', '', 3, 3, 2, False, True, True),
        (1, 'Moisés', '', '', '', 3, 2, 3, False, True, True),
    ],
    "ARTFACTS": [
        (2, 'Arca da Aliança', '', '', '', 5, 0, 0, False, True, False),
        (2, 'Arca de Noé', '', '', '', 5, 0, 0, True, False, True),
        (2, 'Botas do Evangelho', '', '', '', 2, 0, 0, True, False, True),
        (2, 'Cajado de Moisés', '', '', '', 2, 0, 0, True, True, True),
        (2, 'Capacete da Salvação', '', '', '', 1, 0, 0, True, True, True),
        (2, 'Cinturão da Verdade', '', '', '', 4, 0, 0, False, True, True),
        (2, 'Couraça da Justiça', '', '', '', 3, 0, 0, True, True, True),
        (2, 'Escudo da Fé', '', '', '', 1, 0, 0, False, True, True),
        (2, 'Espada do Espírito', '', '', '', 3, 0, 0, True, True, True),
        (2, 'Os 10 Mandamentos', '', '', '', 6, 0, 0, True, False, False),
    ],
    "SINS": [
        (4, 'Fruto Proibido', '', '', '', 3, 0, 0, False, True, False),
        (4, 'Idolatria', '', '', '', 2, 0, 0, False, True, False),
        (4, 'Traição', '', '', '', 2, 0, 0, False, True, False),
    ],
    "MIRACLES": [
        (3, 'Cordeiro de Deus', '', '', '', 4, 0, 0, False, True, False),
        (3, 'Dilúvio', '', '', '', 6, 0, 0, False, True, False),
        (3, 'Fogo do Céu', '', '', '', 3, 0, 0, False, True, False),
        (3, 'Força de Sansão', '', '', '', 2, 0, 0, False, True, False),
        (3, 'Liberação Celestial', '', '', '', 2, 0, 0, False, True, False),
        (3, 'No Céu tem Pão', '', '', '', 3, 0, 0, False, True, False),
        (3, 'Passagem Segura', '', '', '', 4, 0, 0, False, True, False),
        (3, 'Proteção de  Divina', '', '', '', 1, 0, 0, False, True, False),
        (3, 'Ressurreição', '', '', '', 3, 0, 0, False, True, False),
        (3, 'Restauração de Fé', '', '', '', 2, 0, 0, False, True, False),
        (3, 'Sabedoria de Salomão', '', '', '', 1, 0, 0, False, True, False),
        (3, 'Sarça Ardente', '', '', '', 2, 0, 0, False, True, False),
    ]
}
